global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8000']
    metrics_path: /metrics

  - job_name: 'sales-service'
    static_configs:
      - targets: ['sales-service:8000']
    metrics_path: /metrics
